spring:
  application:
    name: dream-shops

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        lob:
          non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/dreamshops
    username: root
    password: "#Gigi1704"

